"""Generate deterministic Apache Arrow interoperability fixtures.

The binary artifacts are generated by PyArrow rather than hand-authored. This
script is intentionally small enough to audit and pins the producer version in
requirements-dev.txt.
"""

from pathlib import Path

import pyarrow as pa


ROOT = Path(__file__).resolve().parents[1]
FIXTURES = ROOT / "fixtures"


def main() -> None:
    FIXTURES.mkdir(exist_ok=True)
    schema = pa.schema(
        [
            pa.field("city", pa.string(), nullable=False),
            pa.field("temperature_c", pa.int32(), nullable=True),
            pa.field("active", pa.bool_(), nullable=True),
            pa.field("score", pa.float64(), nullable=True),
        ]
    )
    batch = pa.record_batch(
        [
            pa.array(["Shenzhen", "Paris", "Unknown", "Tokyo"], pa.string()),
            pa.array([31, 19, None, 27], pa.int32()),
            pa.array([True, None, False, True], pa.bool_()),
            pa.array([9.5, None, -1.25, 7.0], pa.float64()),
        ],
        schema=schema,
    )
    path = FIXTURES / "pyarrow-basic.arrows"
    with path.open("wb") as sink:
        with pa.ipc.new_stream(sink, schema) as writer:
            writer.write_batch(batch)
    print(f"generated {path.relative_to(ROOT)} ({path.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
