name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hustcer/setup-moonbit@v1
      - run: moon fmt --check
      - run: moon info
      - run: moon check --target all --deny-warn
      - run: moon test --target all --deny-warn
